<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Compartilhado\Dominio\" />
    <Folder Include="Compartilhado\Infraestrutura\" />
    <Folder Include="Compartilhado\Infraestrutura\Arquivos\" />
    <Folder Include="Modulos\Chamados\Dominio\" />
    <Folder Include="Modulos\Chamados\Infraestrutura\" />
    <Folder Include="Modulos\Fabricantes\Dominio\" />
    <Folder Include="Modulos\Fabricantes\Infraestrutura\" />
  </ItemGroup>

</Project>
